sonar.projectKey=superuart-backend
sonar.projectName=SuperUART Backend
sonar.sourceEncoding=UTF-8

sonar.sources=src/app
sonar.tests=tests

sonar.exclusions=**/__pycache__/**,**/coverage/**,**/dist/**,**/*.lock,src/migrations/**
sonar.coverage.exclusions=src/migrations/**,src/app/core/db/models.py

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.qualitygate.wait=true
