apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/webserialsys/superuart/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/webserialsys/superuart/frontend:latest
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_API_BASE_URL
              value: ""
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/webserialsys/superuart/backend:latest
          imagePullPolicy: Always
          command:
            - uv
            - run
            - --no-sync
            - arq
            - src.app.core.worker.settings.WorkerSettings
