apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: migrate
          image: ghcr.io/webserialsys/superuart/backend:v0.1.5
          imagePullPolicy: Always
          args:
            - migrate
          envFrom:
            - configMapRef:
                name: superuart-config
            - secretRef:
                name: superuart-secret
